Parameters:
  envPrefixCommon:
    Type: String
    Default: 'prod'
    AllowedValues:
      - alpha
      - delta
      - stage
      - prod
      - loadtest
      - sandbox
    Description: Common prefix for the Environment you want to create
    Type: String
    Default: 'commonapp.net'
    AllowedValues:
      - devca.net
      - commonapp.net
      - commonapp.org
    Description: Top Level Domain for Environment
  envYear:
    Type: String
    Default: '18'
    AllowedValues:
      - 17
      - 18
      - 19
      - 20
    Description: '2 Digit year of the environment'
  paramBucketName:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
    Description: The Name od the Parambucket to test
    MaxLength: '16'
    MinLength: '1'
    NoEcho: 'true'
    Type: String
    
Resources:
  AccountRolloverBucket:
    Type: AWS::S3::Bucket
    Properties:
        BucketName: !Sub ca.${envPrefixCommon}${envYear}.account-rollover 

  PartnerBuckets:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ca.${envPrefixCommon}${envYear}.partners

  PARAMBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ca.${envPrefixCommon}${envYear}.${paramBucketName}