Parameters:
  envPrefixCommon:
    Type: String
    Default: 'playpen'
    AllowedValues:
      - alpha
      - delta
      - stage
      - prod
      - loadtest
      - sandbox
      - playpen
      - test-playpen
    Description: Common prefix for the Environment you want to create
  cidrBlock:
    Type: String
    Default: 10.3
    Description: Preferred cidr for VPC
  envRegionLabel:
    Type: String
    Default: poc
    Description: Region name prefix for security groups
    NoEcho: 'true'
  commonDomain:
    Type: String
    Default: 'commonapp.net'
    AllowedValues:
      - devca.net
      - commonapp.net
      - commonapp.org
    Description: Top Level Domain for Environment
    
Resources:
  PARAMBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ca.${envPrefixCommon}${cidrBlock}.${envRegionLabel}.${commonDomain}